[project]
name = "crawl4ai-local-for-windows"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fixalot", email = "35915923+fix-a-lot@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "crawl4ai>=0.9.2",
    "mcp[cli]>=2.0.0",
]

[project.scripts]
main = "crawl4ai_local_for_windows.server:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
